# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gary Rozanc Teaching Blog
email: grozanc@umbc.edu
description: > # this means to ignore newlines until "baseurl:"
  Gary is an Assistant Professor at the University of Maryland, Baltimore County. While Gary loves all things design, he specializes in teaching responsive web and user experience design.
baseurl: "students" # the subpath of your site, e.g. /blog
url: "https://garyrozanc.com/" # the base hostname & protocol for your site
twitter_username: garyrozanc
github_username:  garyrozanc

# Build settings
markdown: kramdown
permalink: /:categories/:title.html
exclude: [config.codekit3]


